variable "prod_vpc_namespace" {}
variable "prod_vpc_id" {}
variable "prod_private_subnets" {}
variable "prod_database_subnets" {}
variable "hadr_private_subnets" {}
variable "hadr_database_subnets" {}
variable "prod_vpc_cidr" {}
variable "hadr_vpc_namespace" {}
variable "hadr_vpc_id" {}
variable "hadr_vpc_cidr" {}
variable "kms_key_id" {}
variable "pw_length" {}
variable "pw_special" {}
variable "pw_override" {}
variable "environment" {}
variable "db_main_allocated_storage" {}
variable "db_main_max_allocated_storage" {}
variable "backup_retention_period" {}
variable "backup_window" {}
variable "multi_az" {}
variable "storage_type" {}
variable "engine_type" {}
variable "engine_version" {}
variable "db_instance_class" {}
variable "db_encrypted" {}
variable "prod_db_namespace" {}
variable "hadr_db_namespace" {}
